// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InviteModalController from "./invite_modal_controller"
application.register("invite-modal", InviteModalController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)
